Update Ruby version in action
The action failed with this error:

```
ERROR:  Error installing github-pages:
	There are no versions of nokogiri (>= 1.16.2, < 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	nokogiri requires Ruby version >= 3.0, < 3.4.dev. The current ruby version is 2.7.8.225.
```